Allow the publisher to define the logStreamName per job
jenkinsci/aws-cloudwatch-logs-publisher-plugin pull request #2
Opened 2017-05-22 14:39 UTC by samdunne

2017-05-22 17:35 UTC, elifarley requested changes
Hi,
Please take a look at my comments on this review.

And thanks for your contribution!

2017-05-22 17:35 UTC, elifarley commented on src/main/resources/jenkins/plugins/awslogspublisher/AWSLogsPublisher/config.jelly
> +    <f:entry title="${%Log group name}" field="logStreamName">
It should read "%Log stream name".

2017-05-22 17:35 UTC, elifarley commented on src/main/java/jenkins/plugins/awslogspublisher/AWSLogsPublisherDescriptor.java
> +        /**
Lines 31 - 33: No need to change them.

2017-05-26 14:28 UTC, merged

2017-06-12 16:06 UTC, samdunne commented
Can we possibly release this change?